# Parses the vocabulary of chord qualities

import pickle


START = (0,)
END = (-1,)

# data: as generated by parsing.py
def getVocab(data):
    v = set([START, END])
    for phrase in data:
        v.update(set(phrase[1]))
    return v

#generates and pickles the vocabulary
def main():
    data = pickle.load(open('parsed_data.p', 'rb'))
    vocab = getVocab(data)
    print(len(vocab), 'unique chords')
    pickle.dump(vocab, open('vocab.p', 'wb'))

if __name__ == '__main__':
    main()
